name: Publish
on:
  push:
    branches:
      - main
  release:
    types: [created]
jobs:
  publish-package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Setup .npmrc file to publish to GitHub Packages
      - uses: actions/setup-node@v1
        with:
          node-version: '20.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@conniehealth/open-ai-assistant-wrapper'
      - run: npm run clean
      - run: npm install
      - run: npm run build
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
